### ISSUE TITLE
refit generates a warning

### ISSUE THREAD

**Issue by mbanghart** [lme4/lme4#354]
Refit generates a warning when update does not.  The attached file has code to reproduce the error and the result that I got from running the error.  
Thanks for looking into this.
Mark 
[refitWarning.txt](https://github.com/lme4/lme4/files/103489/refitWarning.txt)

**Comment by bbolker** [comment]
I think this is fixed in the development version. Would it be feasible to you install the development version via `devtools::install_github()` (requires compilers etc. be installed) and confirm that it resolves the issue for you? If not, we can update the binaries of the development version posted on r-forge, but that will take slightly more effort on our part.

**Comment by mbanghart** [comment]
Ben,

I checked it this morning after loading the development version of lme4.  I cleared the workspace, restarted the session, reloaded lme4, and confirmed that I had version 1.1.11 loaded.  I am still getting a warning using refit and there is no warning from the call to update or the call to glmer with the new response.  Sorry.

Mark


________________________________

**Comment by bbolker** [comment]
results from `sessionInfo()` please ... ?

**Comment by mbanghart** [comment]
Ben,
sessionInfo() is at the bottom of the output.  Let me know if there is anything else I can do to help with this.
Mark

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> #
> # Test refit, update and new call to glmer produce same results
> #
> 
> library(lme4)
Loading required package: Matrix
Warning message:
package ‘Matrix’ was built under R version 3.2.3 
> packageVersion("lme4")
[1] ‘1.1.11’
> 
> # Generate a data set with one fix effect and one random
> #
> set.seed(182417)
> numLevels <- 30
> numObs <- numLevels * 100
> f1 <- rnorm(numObs)
> v1 <- factor( rep(1:numLevels,(numObs/numLevels)) )
> rsp <- 0.1*f1 + 0.05*rnorm(numLevels)[as.numeric(v1)] +
+     0.025*rnorm(numObs)
> rspOdds <- exp( rsp )
> prob <- rspOdds/(1+rspOdds)
> brsp <- rbinom(numObs,1,prob)
> mod <- glm(brsp ~ f1,family=binomial)
> rmod <- glmer(brsp ~ f1 + (1|v1),family=binomial)
> 
> # new response variable
> #
> set.seed(650931)
> sim <- simulate(mod)[,1]
> 
> modRefit <- refit(rmod,newresp=sim)
Warning message:
In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.00101612 (tol = 0.001, component 1)
> summary(modRefit)
Generalized linear mixed model fit by maximum likelihood (Laplace  Approximation)
 [glmerMod]
 Family: binomial  ( logit )
Formula: brsp ~ f1 + (1 | v1)

     AIC      BIC   logLik deviance df.resid 
  4163.8   4181.8  -2078.9   4157.8     2997 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.0624 -1.0082  0.9544  0.9910  1.0529 

Random effects:
 Groups Name        Variance  Std.Dev. 
 v1     (Intercept) 2.037e-09 4.513e-05
Number of obs: 3000, groups:  v1, 30

Fixed effects:
            Estimate Std. Error z value Pr(>|z|)
(Intercept)  0.01772    0.03652   0.485    0.628
f1           0.03270    0.03579   0.914    0.361

Correlation of Fixed Effects:
   (Intr)
f1 0.011 
convergence code: 0
Model failed to converge with max|grad| = 0.00101612 (tol = 0.001, component 1)

> 
> modUpdate <- update(rmod,formula="sim~.")
> summary(modUpdate)
Generalized linear mixed model fit by maximum likelihood (Laplace  Approximation)
 [glmerMod]
 Family: binomial  ( logit )
Formula: sim ~ f1 + (1 | v1)

     AIC      BIC   logLik deviance df.resid 
  4163.8   4181.8  -2078.9   4157.8     2997 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.0624 -1.0082  0.9544  0.9910  1.0529 

Random effects:
 Groups Name        Variance Std.Dev.
 v1     (Intercept) 0        0       
Number of obs: 3000, groups:  v1, 30

Fixed effects:
            Estimate Std. Error z value Pr(>|z|)
(Intercept)  0.01771    0.03652   0.485    0.628
f1           0.03269    0.03579   0.914    0.361

Correlation of Fixed Effects:
   (Intr)
f1 0.011 
> 
> modGlmer <- glmer(sim ~ f1 + (1|v1),family=binomial)
> summary(modGlmer)
Generalized linear mixed model fit by maximum likelihood (Laplace  Approximation)
 [glmerMod]
 Family: binomial  ( logit )
Formula: sim ~ f1 + (1 | v1)

     AIC      BIC   logLik deviance df.resid 
  4163.8   4181.8  -2078.9   4157.8     2997 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.0624 -1.0082  0.9544  0.9910  1.0529 

Random effects:
 Groups Name        Variance Std.Dev.
 v1     (Intercept) 0        0       
Number of obs: 3000, groups:  v1, 30

Fixed effects:
            Estimate Std. Error z value Pr(>|z|)
(Intercept)  0.01771    0.03652   0.485    0.628
f1           0.03269    0.03579   0.914    0.361

Correlation of Fixed Effects:
   (Intr)
f1 0.011 
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lme4_1.1-11  Matrix_1.2-3

loaded via a namespace (and not attached):
[1] minqa_1.2.4     MASS_7.3-45     tools_3.2.2     Rcpp_0.12.3    
[5] splines_3.2.2   nlme_3.1-124    grid_3.2.2      nloptr_1.0.4   
[9] lattice_0.20-33
>

**Comment by bbolker** [comment]
OK, I can replicate. I think this is the combination of a false positive (along with the many, many others) and the fact that `refit()` and `update()` have slightly different starting conditions.  For example:

```
mm <- list(refit=modRefit,update=modUpdate,denovo=modGlmer)
t(sapply(mm,fixef))
##        (Intercept)         f1
## refit   0.01771730 0.03269799
## update  0.01770956 0.03269151
## denovo  0.01770956 0.03269151
sapply(mm,getME,"theta")
##  refit.v1.(Intercept) update.v1.(Intercept) denovo.v1.(Intercept) 
##          4.512828e-05          0.000000e+00          0.000000e+00
print(sapply(mm,deviance),digits=10)
##       refit      update      denovo 
## 4157.822894 4157.822896 4157.822896 

```

The parameters aren't identical, but they're close enough for practical purposes (it's a little annoying that `refit()` didn't manage to hit the boundary).  The difference in deviance is **very** small.

Solutions:

- provide a set of parameters to allow `refit()` to mimic `update()` more closely (and vice versa?)
- turn up threshold on warnings across the board
