### ISSUE TITLE
Changes to worse in reverse dependencies under lme4 2.0.0

### ISSUE THREAD

**Issue by annahuynhly** [lme4/lme4#886]
The sequel to https://github.com/lme4/lme4/issues/882...

See [CHANGES_1.1-38_2.0.0.tar.gz](https://github.com/user-attachments/files/23869513/CHANGES_1.1-38_2.0.0.tar.gz)

**Comment by jaganmn** [comment]
The number of broken packages is 20 but the number of distinct causes seems small.

PS: Nice work. :-)

**Comment by jaganmn** [comment]
Among the 20 broken strong reverse dependencies I count 9 distinct problems:
|Package|Cause|Location|
|---:|:---|:---|
|**afex**|reflects old `\|\|` behaviour|`tests/testthat/test-mixed-structure.R`|
|**blme**|tests formal arguments of deviance functions and `lme4::updateStart`; does `checkConv(ctrl=NULL)` which is not supported; see also 2c8b480|`blme::blmer`|
|**designr**|reflects old `\|\|` behaviour|`vignette("power-analyses")`, `designr::extractTerms`|
|**GLMpack**|uses `cs` as non-special in model formula|`example("mexico")`|
|**lme4breeding**|reflects old `\|\|` behaviour|`vignette("lmebreed.gxe")`|
|**lmerTest**|tests formal arguments of deviance functions; see also 2c8b480|`lmerTest::as_lmerModLmerTest`|
|**merDeriv**|`nAGQ <= 25L` is newly tested by `getME(., "devfun")`|`inst/tinytest/test_merDeriv.R`|
|**REndo**|tests for `VarCorr` error (which was a bug) that no longer occurs|`tests/testthat/test-inputchecks_multilevel.R`, `REndo::multilevelIV`|
|rstanarm|reflects old `\|\|` behaviour|`tests/testthat/test_stan_functions.R`, local `test_lme4`|

**Comment by bbolker** [comment]
For `GLMpack`: I *might* be able to rework the logic in `reformulas` to ignore specials unless they're at the head of an expression containing `|` ...  (i.e. that would distinguish between `cs(f)` and `cs(1|f)`)

**Comment by jaganmn** [comment]
> We could improve back-compatibility for the old `||` behaviour by allowing an option setting that would specify the `expand_doublevert_method` argument to `findbars_x` with `lFormula`/`glFormula` ...

That makes sense.  For the maintainers, enabling the option will be much easier than adapting to the new behaviour.

> For `GLMpack`: I _might_ be able to rework the logic in `reformulas` to ignore specials unless they're at the head of an expression containing `|` ... (i.e. that would distinguish between `cs(f)` and `cs(1|f)`)

That also makes sense.

If you are able to make those changes soon, then we can try to notify the `||`-affected maintainers and the **GLMpack** maintainer next week-ish, before the break.  I will go ahead and contact the maintainers of **REndo**, **blme**, and **lmerTest**, maybe providing patches.

The **merDeriv** issue revealed to me that the test for `nAGQ <= 25L` in `mkGlmerDevfun` is not actually triggered by `glmer` when `control$nAGQ0initStep` is `TRUE` (as by default), because then the call to `mkGlmerDevfun` uses `nAGQ = 0L`.  The resulting deviance function is updated to `nAGQ > 0L` by `updateGlmerDevfun`, which doesn't test `nAGQ <= 25L`.

We could be principled and add a symmetric test in `updateGlmerDevfun`, and we might then catch more packages like **merDeriv**.  Or we could be unprincipled and increase the limit to 30, which happens to be what **merDeriv** tries.  Or we could do both things ...  I don't have much of an opinion because I don't deeply understand the basis for the original limit.

**Comment by bbolker** [comment]
I think the `nAGQ` limit was probably (?) originally there because (1) the weights are hard-coded (so there has to be *some* limit) and (2) @dmbates figured that 25 was good enough for practical purposes:

> A model with a single, scalar random-effects term could reasonably use up to 25 quadrature points per scalar integral.

However, in 2014 (68840ca41f05c6) I added info for weights up to nAGQ=100.

I've updated docs and code (and added a test for `nAGQ <= 100L` to `updateGlmerDevfun`)

We should re-check after merging #892, which should make the `||`-based problems go away ...

**Comment by bbolker** [comment]
@dmbates good to know, and makes allowing up to 100 quad points seem kind of silly, but I don't see a reason at this point to actively revert/*decrease* the max allowed `nAGQ` value ... do you? (Perhaps more relevant to finally get around to implementing `nAGQ` for 2-dim random effects ... I have a postdoc offer open for someone to work on AGQ, maybe it'll happen ...)

**Comment by jaganmn** [comment]
You could either register formally that `vcmat_us` inherits from `matrix` and `array` with

```
setOldClass(c("vcmat_us", "matrix", "array"))
```

or do `as(as(x, "sparseMatrix"), "CsparseMatrix")`.  **Matrix** defines a method for `coerce` with signature `c(from="ANY", to="sparseMatrix")` but not one with signature `c(from="ANY", to="CsparseMatrix")`.  (I looked at `showMethods("coerce")` to refresh my memory.)

**Comment by bbolker** [comment]
- GLMpack: fixed by `reformulas` update, but could also be easily worked around (name the "center-and-scale" utility function something other than `cs()`)
-  REndo: ?
- equatiomatic: ?
- glmmTMB: fixed in development version (note we'll need to do reverse dependency checks etc. prior to submitting a new version ...)
- rockchalk: "formatVC not found" (may need to import from `reformulas` instead of `lme4` ?)
-  tram: comparison fails because of changed VC class `vcmat_us` (follow `glmmTMB` example in 0106356b57079 ?)

**Comment by jaganmn** [comment]
If **reformulas** is stable, then it can just go to CRAN after the break.  Ideally, **GLMpack** would not have to change valid code.

I've already contacted the **REndo** maintainer.

**equatiomatic** is still broken because the `||` fix was incomplete.  Compare

```
formula(lmer(Reaction ~ Days + (Days || Subject), sleepstudy))
```

under **lme4** 1.1-38 and 2.0.0.  **equatiomatic** relies on the old behaviour.

Since **glmmTMB** could do a hotfix release after the break with just the patch to its tests, its reverse dependency checks don't seem like a real blocker for **lme4**.  But you can decide and communicate with them.

I'll send the **rockchalk** maintainer an e-mail.

The problem with **tram** is just that the class attribute is newly printed.  We can define methods for `print` to suppress printing of the attribute or to print something nicer.  If we do the second thing (or if we do nothing), then the **tram** maintainer would have to adjust their test by unclassing before printing and/or using

```
## IGNORE_RDIFF_BEGIN
## IGNORE_RDIFF_END
```

in which case I could contact them.

I didn't get a response from the maintainers of **blme** or **lmerTest**, so I might nudge them after the break, ideally with a date in mind for submitting **lme4** 2.0.0.

**Comment by jaganmn** [comment]
@annahuynhly Are you expecting to have more time for the vignette in the next couple of weeks?  It's OK if not, but it would be good to know if so.

I haven't hear anything from the **blme** maintainer, so I created a GH issue: vdorie/blme#18.

I'm refreshing the reverse dependency checks now, so we'll know in a few hours where things stand.

**Comment by jaganmn** [comment]
> I'm refreshing the reverse dependency checks now, so we'll know in a few hours where things stand.

No new changes to worse, and **equatiomatic** is no longer broken.

**Comment by jaganmn** [comment]
The development versions of **blme** and **lmerTest** pass their checks under **lme4** 1.1-38 and under 2.0-0.  **REndo** is the only package whose maintainer hasn't replied, hence: mmeierer/REndo#93.

Once the vignette is done and we have notified strong reverse dependencies about changes, we should be ready to submit.

**Comment by bbolker** [comment]
@annahuynhly and I realized that #852 actually reflects a long-standing bug (in printing RE variances from GLMMs with free scale parameters), which I'd like to fix before releasing. Otherwise I think we're ready to go. The `Rendo` package maintainers said ["We will look into this shortly"](https://github.com/mmeierer/REndo/issues/93#issuecomment-3716768351) two weeks ago, so I think we've done our due diligence ...

**Comment by jaganmn** [comment]
Yes, updates to **blme** and **lmerTest** were published to CRAN.  I'll rerun the reverse dependency checks without the work-arounds for those packages, to be sure that things are OK.  I agree that it would be nice to eventually incorporate some of the stuff from e-mail into the vignette.  I don't have time at the moment but there is no harm in releasing an **lme4** version 2.0-1 with more rigorous documentation.

**Comment by bbolker** [comment]
hopefully fixed now ...

**Comment by jaganmn** [comment]
I'll run the checks again today/tonight.

**Comment by jaganmn** [comment]
No, I became preoccupied with something else ...  I finally started the checks a few hours ago, so we might as well wait until morning to submit.

**Comment by jaganmn** [comment]
We still have this issue:

```
$ R CMD build --compact-vignettes=gs+qpdf .
* checking for file './DESCRIPTION' ... OK
* preparing 'lme4':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package (it is needed to process help pages)
* saving partial Rd database
* creating vignettes ... ERROR
--- re-building ‘autoscale.Rmd’ using rmarkdown
--- finished re-building ‘autoscale.Rmd’

--- re-building ‘covariance_structures.Rmd’ using rmarkdown

Quitting from covariance_structures.Rmd:333-344 [compare-cov]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<error/rlang_error>
Error in `ss[x, "Std. Error"]`:
! no 'dimnames' attribute for array
---
Backtrace:
    ▆
 1. ├─global all.equal.nocheck(ranef(lme4.us)$group, ranef(glmmTMB.us)$cond$group)
 2. │ └─methods::is(y, "Matrix")
 3. ├─nlme::ranef(glmmTMB.us)
 4. └─glmmTMB:::ranef.glmmTMB(glmmTMB.us)
 5.   └─base::lapply(inds, function(x) ss[x, "Std. Error"])
 6.     └─glmmTMB (local) FUN(X[[i]], ...)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: processing vignette 'covariance_structures.Rmd' failed with diagnostics:
no 'dimnames' attribute for array
--- failed re-building ‘covariance_structures.Rmd’

--- re-building ‘lmerperf.Rmd’ using rmarkdown
--- finished re-building ‘lmerperf.Rmd’

--- re-building ‘Theory.Rnw’ using knitr
--- finished re-building ‘Theory.Rnw’

--- re-building ‘lmer.Rnw’ using knitr
--- finished re-building ‘lmer.Rnw’

--- re-building ‘PLSvGLS.Rnw’ using Sweave
--- finished re-building ‘PLSvGLS.Rnw’

SUMMARY: processing the following file failed:
  ‘covariance_structures.Rmd’

Error: Vignette re-building failed.
Execution halted
```

**Comment by jaganmn** [comment]
It was my fault, I had the development version of **Matrix** installed, and that breaks the vignette (a problem for later ...).

**Comment by jaganmn** [comment]
`R CMD check --as-cran` fails under R-devel (r89382): [00check.log](https://github.com/user-attachments/files/25171148/00check.log) [AAAtest-all.Rout.fail.log](https://github.com/user-attachments/files/25171149/AAAtest-all.Rout.fail.log)

> Is the Matrix-devel incompatibility something that's worth fixing now so that it doesn't break later ?

I'm not sure yet which of **Matrix** and **lme4** needs fixing to resolve it.  I'll look later tonight and try to figure it out.

**Comment by bbolker** [comment]
Sigh. 29 failures, of which only 3 were expected, what did we miss? Hopefully there is a small number of ultimate causes.

*** Changes to worse in reverse dependencies ***
Debian: <https://win-builder.r-project.org/incoming_pretest/lme4_2.0-0_20260209_205331/reverseDependencies/summary.txt>
ALDEx3, GimmeMyStats, MedianaDesigner, REndo, broom.mixed, buildmer, cocoon, doremi, effectsize, embed, fullfact, galamm, grafify, iSTAY, insight, jstable, lucid, mecor, metan, mlmpower, mlr3pipelines, papaja, parameters, readyomics, robustlmm, rockchalk, rstanarm, rtpcr, tram
 


[lme4_bad.txt](https://github.com/user-attachments/files/25210256/lme4_bad.txt)

**Comment by jaganmn** [comment]
**lucid** is broken due to the new special casing of GLMMs by `VarCorr.merMod`.

**Comment by jaganmn** [comment]
```
> mkVarCorr(sc = 1, cnms = c("A" = "a"), nc = 1L, theta = 1, nms = "A")
Error: unable to find an inherited method for function 'getTheta' for signature 'object = "NULL"'
```

**Comment by bbolker** [comment]
I need to think about this a little bit more, but *if* the printing is smart enough on the other end, I would want to skip generating the full matrices for all of the structured matrix types; people sometimes use these structures to fit *very* large correlation matrices (e.g. AR1 for a time series with 10,000 steps), in which case we really don't want to try to generate the full correlation matrix, even by default ...

**Comment by bbolker** [comment]
`broom.mixed` is updated on CRAN. @runehaubo is ready to post `lmerTest` to CRAN if we want. I haven't had the time/brain space to think about the full-correlation-matrix issue properly yet ...

**Comment by jaganmn** [comment]
> As long as we don't think we're making big backward-compatibility headaches for ourselves if/when we try to change this at some point in the future, I think I'm OK with leaving it the way it is.

If we agree that the complexity introduced by `full_cor` is not really helping in the **lme4** context, then my preference would be to get rid of `full_cor` and behave as previously always documented, constructing the correlation matrix unconditionally, until someone comes along with a real problem.  One fewer breaking change would be nice ...

> * contact Manual Koller [kollerma@proton.me](mailto:kollerma@proton.me) (`robustlmm` maintainer) about needed fixes
> * ask [@runehaubo](https://github.com/runehaubo) to upload fixed `lmerTest`, wait until it is on CRAN
> * re-run revdep checks one last (????) time ...

That sounds good.  I'll leave the communication with Manuel and Rune to you and re-run the reverse dependency checks as soon as we're ready.

**Comment by jaganmn** [comment]
One test that passes under R-patched is failing under R-devel (r89435) - it relates to influence stuff as you might expect ...

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-methods.R:901:3'): rstudent matches for zero-var cases ───────
Expected `suppressWarnings(rstudent(glmer_zero))` to equal `rstudent(glm_zero)`.
Differences:
82/120 mismatches (average diff: 0.122)
[1]   1.355 -  1.528 == -0.1726
[2]  -0.772 - -0.723 == -0.0494
[3]   0.866 -  0.940 == -0.0741
[4]  -0.791 - -0.739 == -0.0521
[5]   0.842 -  0.912 == -0.0699
[7]   0.323 -  0.335 == -0.0121
[8]  -0.831 - -0.773 == -0.0577
[10]  0.784 -  0.844 == -0.0599
[12] -0.871 - -0.807 == -0.0635
...

[ FAIL 1 | WARN 0 | SKIP 6 | PASS 1775 ]
```

**Comment by jaganmn** [comment]
I think that we should omit the extra row for all GLMMs.  Then we can get rid of the `useSc` attribute of `VarCorr(...)` and the `is_lmm` argument of `mkVarCorr` and use `is.null(sc)` to indicate whether we had an LMM.  That's much simpler ...

**Comment by jaganmn** [comment]
I don't see any code in **lme4** or **reformulas** making use of the new `theta`, `profpar`, and `rho` attributes of the `vcmat_*`.  What is the plan for those attributes?  And if they are not yet used anywhere, then would it make sense to add them to **lme4** only after **reformulas** is taught how to use them (i.e., omit them for now)?

**Comment by bbolker** [comment]
Fixed `projpred` (at least the proximal thing you point out above), left an [issue](https://github.com/sthawinke/smoppix/issues/1) for `smoppix` (I have **no** idea what's going on there ...)  Made a PR for `lucid` which has already been merged.

|Package|Cause|Status|
|---:|:---|:---|
|**REndo**|tests for `VarCorr` error (which was a bug) that no longer occurs|"we will look into this shortly" (issue [here](https://github.com/mmeierer/REndo/issues/93), posted Jan 5)|
|**lucid**|reference values from VarCorr changed|PR accepted in GH|
|**muscat** (BioC)|downstream of `lmerTest`?|? |
|**rockchalk**|"formatVC not found" (may need to import from reformulas instead of lme4 ?)| e-mail sent Jan 1|
|**smoppix** (BioC)|unclear|[issue](https://github.com/sthawinke/smoppix/issues/1)|
|**tram**|comparison fails because of changed VC class vcmat_us (follow glmmTMB example in 0106356b57079 ?)  |e-mail sent Jan 1 |
|**variancePartition** (BioC)|downstream of `lmerTest`? | supposedly fixed Nov 25. BioC uses a different release schedule, so version 1.40.2 is still the "release" version, 1.41.3 is the new "devel" version; which version was tested?|

@jaganmn, can you please double-check (1) that we did contact the `muscat` maintainer and (2) that your tests were run on `variancePartition` 1.40.2 (i.e. this isn't a new problem)?
